name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux_amd64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - run: hugo
      - run: cp -r public/ /root/ 
